export const OPEN_DRAWER = 'OPEN_DRAWER';
export type OPEN_DRAWER = typeof OPEN_DRAWER;

export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export type CLOSE_DRAWER = typeof CLOSE_DRAWER;

export const APP_ONLINE = 'APP_ONLINE';
export type APP_ONLINE = typeof APP_ONLINE;

export const APP_OFFLINE = 'APP_OFFLINE';
export type APP_OFFLINE = typeof APP_OFFLINE;

export const NOTIFICATION_ENABLED = 'NOTIFICATION_ENABLED';
export type NOTIFICATION_ENABLED = typeof NOTIFICATION_ENABLED;

export const NOTIFICATION_SUPPORTED = 'NOTIFICATION_SUPPORTED';
export type NOTIFICATION_SUPPORTED = typeof NOTIFICATION_SUPPORTED;

export const NOTIFICATION_DENIED = 'NOTIFICATION_DENIED';
export type NOTIFICATION_DENIED = typeof NOTIFICATION_DENIED;

export const NOTIFICATION_SKIPPED = 'NOTIFICATION_SKIPPED';
export type NOTIFICATION_SKIPPED = typeof NOTIFICATION_SKIPPED;